package ru.vsu.cs.zmaev.carpartsservice.domain.enums;

public enum PartType {
    OIL_FILTERS,
    AIR_FILTERS,
    FUEL_FILTERS,
    SALON_FILTERS,
    HYDRAULIC_FILTERS,

    BRAKING_PADS,
    BRAKE_DISCS,
    DRUM_BRAKES,
    WEAR_SENSORS,
    BREAK_CALIPER,
    BRAKE_CYLINDERS,
    CLUTCH_CABLES,
    CLUTCH_CONTROL,
    HOSES,

    SHOCK_ABSORBERS,
    BUSHINGS,
    SHOCK_ABSORBER_SUPPORT,
    WHEEL_HUB,
    STABILIZER_POLE,
    BEARINGS,
    SUSPENSION_ARM,
    CUSHIONS,
    SPRINGS,
    AIR_SUSPENSION_COMPRESSORS,
    ANTHERS,
    // Рессора
    SUSPENSION_SPRING,

    TIE_ROD,
    STEERING_TIPS,
    POWER_PUMPS,
    STEERING_LEVERS,
    STEERING_BOOTS,
    STEERING_RESERVOIRS,
    STEERING_GEARS,

    SEALS,
    LIDS_AND_PLUGS,
    ENGINE_GASKET,
    OIL_PUMP,
    ENGINE_SHAFT,
    CONNECTING_ROD_SENSORS,
    VALVE,
    COLLECTOR,
    PISTON_RINGS,
    LARGE_ENGINE_PARTS,
    PISTONS_AND_CONNECTING_RODS,

    SPARK_PLUG,
    IGNITION_COIL,
    HIGH_VOLTAGE_WIRE,
    OXYGEN_SENSOR,
    GENERATOR,
    CONTROL_BLOCK,
    ADAPTER,
    SENSOR,
    STARTER,
    MOTORS,
    RELAY,
    GLOW_PLUG,
    ELECTRIC_CLUTCH,

    V_BELT,
    TIMING_BELT,

    RADIATOR,
    VENTILATOR,
    THERMOSTAT,
    WATER_PUMP,
    DRYER,
    AIR_CONDITIONING_COMPRESSOR,

    MAIN_LIGHTING,
    ADD_LIGHTING,
    LAMPS,

    FUEL_PUMP,
    AIR_FLOW_METERS,
    INJECTOR,
    THROTTLE,
    VACUUM_PUMP,

    CLUTCH_DISC,
    CLUTCH_BASKET,
    DRIVE_SHAFT,
    FLYWHEEL,
    BELT_VARIATOR




    }
